[package]
name = "sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
cynic = { version = "3.12.0", features = ["http-surf"] }
uniffi = { version = "0.31.0", features = ["cli"] }

[build-dependencies]
cynic-codegen = "3.12.0"
uniffi = { version = "0.31.0", features = ["build"] }

[lib]
crate-type = ["cdylib"]
name = "sdk"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dev-dependencies]
insta = "1.46.3"
