[package]
name = "sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
uniffi = { version = "0.31.0", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.31.0", features = ["build"] }

[lib]
crate-type = ["cdylib"]
name = "sdk"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"